### ISSUE TITLE
Custom layout for homepage elements

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#993] opened 2019-03-13 17:31 UTC
Some presses want to be able to customize their home page elements so that they can be laid out in columns (e.g. rendering featured journals and a custom html block side by side)

**Describe the solution you'd like**
Add a "width" attribute to home elements determining if an element should take full/half/third of the width? Perhaps we could use some drag and drop tool for this that then just translates into column sizes for the backend.

**Comment by ajrbyers** [comment] 2020-04-15 20:05
@mauromsl will the new CMS system allow us to do this with the homepage?

**Comment by ajrbyers** [comment] 2022-11-10 16:30
This is a duplicate of work that is proposed as part of the CMS rebuild: https://github.com/BirkbeckCTP/janeway/issues/509

**Closed by ajrbyers** 2022-11-10 16:30 UTC
Labels: new feature
