### ISSUE TITLE
An article can be submitted without an abstract and is accepted

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#568] opened 2018-10-25 06:40 UTC
I thought this would be undesirable and some sort of check should be introduced
https://demojournal.janeway.systems/review/unassigned/article/578/

**Comment by ajrbyers** [comment] 2019-01-21 11:07
Adding this to Trello, please ignore.

**Comment by ajrbyers** [comment] 2019-08-16 11:28
Duplicate of https://github.com/BirkbeckCTP/janeway/issues/1213

**Closed by ajrbyers** 2019-08-16 11:28 UTC
Labels: enhancement
