### ISSUE TITLE
Preprint contact subject

### ISSUE THREAD

**Issue by seismatters** [BirkbeckCTP/janeway#1888] opened 2020-10-25 07:49 UTC
**Is your feature request related to a problem? Please describe.**

As a moderator, we sometimes have to contact the authors of a submission to ask them to tweak the meta-data, submission itself. This contact occurs via an email that pops-up from the 'Contact Author' button. However, it appears that this email/communication is not captured in the 'Log' (unlike, for example, the email automatically dispatched from the system when an authors submission is received, accepted, declined, etc). This would be useful, such that a notification for other moderators is captured there, rather than in the 'Discussions' tab (i.e. updating the Discussions tab requires another manual entry). Might this be possible? Thanks! Chris

**Comment by ajrbyers** [comment] 2020-10-26 20:23
I think this is a duplicate of https://github.com/BirkbeckCTP/janeway/issues/1887

**Closed by ajrbyers** 2020-10-26 20:23 UTC
Labels: new feature
