### ISSUE TITLE
Option to add abstract to peer review invite email and accept/decline page

### ISSUE THREAD

**Issue by jfrome1** [BirkbeckCTP/janeway#2000] opened 2021-01-30 00:54 UTC
**Is your feature request related to a problem? Please describe.**
Peer review invitations include only submission titles, which is not enough information for potential reviewers to decide whether or not to accept the invitation.

**Describe the solution you'd like**
Allow options to automatically include the abstract for a submission in two places: 1) the template for the peer review invitation email 2) the accept/decline page that is shown after the reviewer includes the accept/decline link.

**Describe alternatives you've considered**
Force reviewers to decide accept/decline based on submission title alone.

**Comment by jfrome1** [comment] 2021-01-31 03:47
Relatedly, add option to automatically add the abstract and keywords to the manuscript that peer reviewers download. I'd like the keywords on the 1) and 2) above also.

**Comment by ajrbyers** [comment] 2021-03-24 10:03
This is a duplicate of the 1.3.10 issue https://github.com/BirkbeckCTP/janeway/issues/2102. Closing now.

**Closed by ajrbyers** 2021-03-24 10:03 UTC
Labels: new feature
