### ISSUE TITLE
About this Journal Text Block problem

### ISSUE THREAD

**Issue by philippagrand** [BirkbeckCTP/janeway#3690] opened 2023-09-12 17:13 UTC
**Describe the bug**
Changing text in the About this Journal Block in Manager leads to random resizing of different sections of the text, deletion of some of the text and is generally not easy to use.  Text on the website appears in bold, even though bold has not been used at the back end.

**Janeway version**
1.5.0

**To Reproduce**
1. Go to Manager/Journal Home Settings/About this Journal
2. Click into the Description text box
3. Type text into the box or make changes such as changing font size, changing text type.

**Expected behavior**
I expect to edit text in the Description text box in a straightforward easy way so that any changes I make are then implemented on the front end without further problems - such as random re-spacing, random deletion of text, bolding when bold function not utilised, different paragraphs being different fonts appear resulting in it taking much longer to edit the text than it should. 

**Screenshots**

## Front-end Issues
If the issue is front-end specific please add the following details:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ajrbyers** [comment] 2023-09-12 17:22
@philippagrand can you screenshot and example or link to an example? Can you also confirm if the content was pasted from, for example, Word, or another processor?

**Comment by philippagrand** [comment] 2023-09-12 20:49
I'm a bit reluctant to screenshot or send an example as I know that the formatting will just go haywire again and I'll have to spend time correcting it (I did finally get the text to do what I wanted it to do).  

I was working with text that was already in the text box so it wasn't copied and pasted from elsewhere.  I did eventually use an HTML washer to sort the text out as it just wouldn't behave...

**Comment by ajrbyers** [comment] 2023-09-12 20:50
> I'm a bit reluctant to screenshot or send an example as I know that the formatting will just go haywire again and I'll have to spend time correcting it (I did finally get the text to do what I wanted it to do).
> 
> I was working with text that was already in the text box so it wasn't copied and pasted from elsewhere. I did eventually use an HTML washer to sort the text out as it just wouldn't behave...

I can almost guarantee that the weirdness you were seeing is caused by the content having been pasted in previously. We have a fix for this where all that crap is stripped out automatically coming in 1.5.1.

**Comment by ajrbyers** [comment] 2024-02-22 10:53
@philippagrand we have a change in 1.5.1 that introduced TinyMCE (a new rich text editor) that clears out erroneous styling and should resolve this issue.

**Closed by ajrbyers** 2024-02-22 10:53 UTC
Labels: bug
