### ISSUE TITLE
journal.models.ArticleOrdering shouldn't hold a key to section

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#852] opened 2019-02-06 17:54 UTC
Both `Article` and `ArticleOrdering` hold a key to section, which could lead to de-synch between the two (If the article is changed to another section, its ArticleOrderings will be pointing at old section)

**Comment by ajrbyers** [comment] 2019-08-16 11:41
Duplicate of https://github.com/BirkbeckCTP/janeway/issues/609

**Closed by ajrbyers** 2019-08-16 11:41 UTC
Labels: bug
