### ISSUE TITLE
Workflow Forloop Should Check Not Null

### ISSUE THREAD

**Issue by ccaadeh** [BirkbeckCTP/janeway#627] opened 2018-11-19 10:18 UTC
Logged in with privileged account:
Go to Dashboard>Publication Schedule:
https://demojournal.janeway.systems/manage/articles/schedule/

Yet Another Article #2 ready for publication:
![screenshot 25](https://user-images.githubusercontent.com/44443205/48700527-18721280-ebe4-11e8-8e6e-366f33703771.png)

However, if you click on the Article you get an error (I spoke to Andy and he thought "It looks like something to do with the Workflow element system."

Request Method: | GET
-- | --
https://demojournal.janeway.systems/manage/archive/article/590/
1.11.16
NoReverseMatch
Reverse for '' not found. '' is not a valid view function or pattern name.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Mon, 19 Nov 2018 10:16:55 +0000

Error during template rendering
In template /home/martindev/demo/janeway/src/templates/admin/elements/article_jump.html, error at line 11

Reverse for '' not found. '' is not a valid view function or pattern name.

{% load securitytags %}
--
 
{% is_editor as editor %}
 
{% if editor %}
<button class="tiny secondary button float-right dropdown" data-toggle="articledropdown">Article Jump</button>
<div class="dropdown-pane bottom small" id="articledropdown" data-dropdown>
<ul>
{% for stage in article.workflow_stages %}
<li>
<a href="{% url stage.element.jump_url article.pk %}">{{ stage.element.element_name\|capfirst }}</a>
</li>
{% endfor %}
<li><a href="{% url 'manage_article_log' article.pk %}">Log</a></li>
<li><a href="{% url 'document_management' article.pk %}?return={{ request.path }}">Documents</a></li>
{% if article.is_published %}
<li><a href="{{ article.url }}">Live Article</a></li>{% endif %}
{% if request.user.is_superuser %}
<li><a target="_blank" href="/admin/submission/article/{{ article.pk }}/">Admin <i
class="fa fa-external-link"></i></a></li>
{% endif %}

If you click on the DOI, you get:

Request Method: | GET
-- | --
https://demojournal.janeway.systems/edit/article/590/ident/?return=/manage/articles/schedule/
1.11.16
NoReverseMatch
Reverse for '' not found. '' is not a valid view function or pattern name.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Mon, 19 Nov 2018 10:17:52 +0000

**Comment by ccaadeh** [comment] 2018-11-20 08:13
Trying to use 'View' for  the same article 'Yet Another One #2' at Dashboard>Back Content Plugin>
https://demojournal.janeway.systems/plugins/back_content/
unsurprisingly yields another error:

Request Method: | GET
-- | --
https://demojournal.janeway.systems/plugins/back_content/article/590/
1.11.16
NoReverseMatch
Reverse for '' not found. '' is not a valid view function or pattern name.
/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 497
/home/martindev/virtualenv/demo_janeway_src/3.5/bin/python3.5
3.5.6
['/home/martindev/demo/janeway/src',  '/home/martindev/demo/janeway/src',  '/opt/passenger-5.1.12-1.el7.cloudlinux/src/helper-scripts',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python35.zip',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/plat-linux',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib64/python3.5/lib-dynload',  '/opt/alt/python35/lib64/python3.5',  '/opt/alt/python35/lib/python3.5',  '/home/martindev/virtualenv/demo_janeway_src/3.5/lib/python3.5/site-packages',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-bootstrap4',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/foundationform',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-mailgun',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/dynamicsites',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/ebooklib',  '/home/martindev/virtualenv/demo_janeway_src/3.5/src/django-materialize',  '/path/to/installation/',  '/path/to/your/virtualenv/name/lib/python3.5/site-packages/',  '/home/martindev/demo/janeway/src/plugins']
Tue, 20 Nov 2018 08:13:27 +0000

**Comment by ajrbyers** [comment] 2018-11-20 08:31
These are the same error.

**Comment by ajrbyers** [comment] 2019-01-21 11:05
Adding this to Trello, please ignore.

**Comment by mauromsl** [comment] 2019-02-06 18:00
I can't reproduce this anymore, might have been fixed in 1.3.2

**Comment by ajrbyers** [comment] 2020-04-15 16:35
This has been fixed as above.

**Closed by ajrbyers** 2020-04-15 16:35 UTC
Labels: bug
