### ISSUE TITLE
Archived articles appear in active submissions

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3424] opened 2023-03-09 13:51 UTC
**Describe the bug**
Articles with `STAGE_ARCHIVED` are not being excluded from the queryset in `core.views.active_submissions`

**Janeway version**
Janeway 1.4.3 (Arizona #5418, 9 Mar 2023)

**To Reproduce**
1. Archive an article
2. Check active submissions

**Expected behavior**
Archived articles articles should be excluded either by modifying the exclude chain in the view, or by using the active_objects manager.

**Comment by ajrbyers** [comment] 2023-03-29 10:26
@joemull I can't replicate this. It looks like a duplicate of https://github.com/BirkbeckCTP/janeway/issues/3311 which has been merged. I can see on the view we're using active_submissions now.

**Closed by ajrbyers** 2023-03-29 10:26 UTC
Labels: bug

**Comment by ajrbyers** [comment] 2023-03-29 14:20
@joemull they are on 1.4.4 now, and the fix was included in that release.

**Comment by joemull** [comment] 2023-03-29 16:03
@ajrbyers are you saying you just put them on 1.4.4? I was hoping to get confirmation that they *weren't* on a branch with the #3311 fix on March 9, when this bug was reported. That would confirm our theory.

**Comment by ajrbyers** [comment] 2023-03-29 16:12
> @ajrbyers are you saying you just put them on 1.4.4? I was hoping to get confirmation that they _weren't_ on a branch with the #3311 fix on March 9, when this bug was reported. That would confirm our theory.

@joemull no, they were already on 1.4.4 when I checked. Mauro will have upgraded them. Manual tests on both master and the Arizona install show that articles in the archive stage are not showing up in the `active_sumbmissions` list anymore.

**Comment by joemull** [comment] 2023-03-29 16:26
OK thanks @ajrbyers
