### ISSUE TITLE
Extra spaces appearing in XML preview

### ISSUE THREAD

**Issue by ECareless** [BirkbeckCTP/janeway#2350] opened 2021-08-13 08:54 UTC
Looks like the XSLT is adding an extra space in XML previews e.g. ( 2018) instead of (2018)

Janeway 1.3

1. Go to C21 journal
2. Go to article 3372 in Proofing https://c21.openlibhums.org/production/3372/preview/8092/ 
2. Click on XML preview
3. Scroll down to References 

Expect to see references formatted like this: Anabel A. (2018) Playing with Feelings: Video Games and Affect, Minneapolis: University of Minnesota Press.

Instead seeing extra spaces before the year ( 2018)

![Screenshot 2021-08-13 at 09 36 39](https://user-images.githubusercontent.com/88839052/129329363-d27804fd-a523-4493-8c47-16d8fc6bb54c.png)

 - iOS
 - Chrome
 - 92

**Comment by joemull** [comment] 2021-11-04 15:39
@ajrbyers this is one of the issues @pgoussy brought up yesterday, and I'm guessing it has to do with XSLT

**Comment by joemull** [comment] 2021-12-08 18:49
Closing this because it is a duplicate of https://github.com/BirkbeckCTP/janeway/issues/2308

**Closed by joemull** 2021-12-08 18:49 UTC
Labels: bug, mpub, xslt
