### ISSUE TITLE
CC Licence info overhangs box

### ISSUE THREAD

**Issue by rossmounce** [BirkbeckCTP/janeway#357] opened 2018-02-01 09:54 UTC
Google Chrome Version 64.0.3282.119 (Official Build) (64-bit), running on Win 10 Enterprise build 14393.2007 https://orbit.openlibhums.org/article/doi/10.16995/orbit.219/

![capture2](https://user-images.githubusercontent.com/824120/35672225-c0d5944a-0735-11e8-9ed5-21e340bed5c1.JPG)

**Comment by ajrbyers** [comment] 2018-02-01 09:57
Hey @rossmounce this is a duplicate of #356

**Closed by ajrbyers** 2018-02-01 09:57 UTC
